# Delete these routes and define your own shop routes here

prugala_sylius_allegro_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: PrugalaSyliusAllegroPlugin:Greeting:staticallyGreet
        name: ~

prugala_sylius_allegro_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: PrugalaSyliusAllegroPlugin:Greeting:dynamicallyGreet
        name: ~
